services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

  ultra-backend:
    container_name: ultra-backend
    build:
      context: ./services/ultra_backend
      dockerfile: Dockerfile
    environment:
      - RABBIT_URL=amqp://guest:guest@rabbitmq:5672/
      - RABBIT_INPUT_QUEUE=piracy_detection_output
      - RABBIT_OUTPUT_QUEUE=piracy_detection_input
    ports:
      - "8054:8054"
    depends_on:
      - rabbitmq
  
  tritonserver:
    image: nvcr.io/nvidia/tritonserver:24.09-py3
    command: ["tritonserver", "--model-repository=/models"]
    volumes:
      - ./model_repository:/models      # Папка с движками моделей и конфигами
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    deploy:                              # Разрешение на использование GPU
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              device_ids: ['0']
              driver: nvidia
  
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.4.0-rc.1
    command: ["milvus", "run", "standalone"]
    security_opt:
    - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"
  
  attu:
    container_name: milvus-attu
    image: zilliz/attu:v2.3.8
    environment:
      MILVUS_URL: standalone:19530
    ports:
      - "8886:3000"
  
  adapter:
    build:
      context: .
      dockerfile: services/adapter/Dockerfile
    environment:
      - LOGURU_LEVEL=INFO
    volumes:
      - ./data:/app/adapter/data
    deploy:
      replicas: 1

  php:
    build:
      context: ./services/web/Docker/php
    volumes:
      - './services/web/src:/var/www/html'

  php-apache-environment:
    container_name: php-apache2
    #image: php:8.0-apache
    build:
      context: ./services/web/Docker/php-apache
    volumes:
      - ./services/web/src:/var/www/html/
      - ./services/web/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - "8080:80"
    environment:
      FASTAPI_URL: "http://ultra-backend:8054/check-video-duplicate"
      HOSTNAME: "php-apache2"
    depends_on:
      - php
      - mysql
      - ultra-backend

  mysql:
    container_name: mysql
    build:
      context: ./services/web/Docker/mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - './services/web/mysql_data:/var/lib/mysql'

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "9100:80"
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysql