FROM python:3.11

RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y

WORKDIR /app

COPY ./docker/requirements.txt ./
RUN pip3 install -r requirements.txt

COPY ./src src/
COPY ./ml_utils ml_utils/
COPY ./configs configs/
COPY adapter.py .
COPY adapter.dev.py .
COPY adapter_hack.py .

ENV LOGURU_COLORIZE "true"

CMD ["python", "adapter_hack.py"]