services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

  ultra-backend:
    container_name: ultra-backend
    build:
      context: ../services/ultra_backend
      dockerfile: Dockerfile
    environment:
      - RABBIT_URL=amqp://guest:guest@rabbitmq:5672/
      - RABBIT_INPUT_QUEUE=input
      - RABBIT_OUTPUT_QUEUE=backend_output
    ports:
      - "8054:8054"
    depends_on:
      - rabbitmq
      - fastapi-answer

  fastapi-answer:
    container_name: fastapi-answer
    build:
      context: ../services/ultra_backend
      dockerfile: fastanswer.Dockerfile
    environment:
      - RABBIT_URL=amqp://guest:guest@rabbitmq:5672/
      - RABBIT_INPUT_QUEUE=input
      - RABBIT_OUTPUT_QUEUE=backend_output
    depends_on:
      - rabbitmq